dataset = 'acic'
model = 'linear'
train_n = 5
test_n = 3
decision_n = 2
query_n = 2
acic_path = '../../datasets/data_cf_all/'
acic_files = ['1/zymu_336720327.csv', '1/zymu_13.csv']
plot_run = True
run_diagnostics = False
